name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up C++ environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build with Makefile
      run: make
