name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up C++ environment
      run: sudo apt-get update && sudo apt-get install -y build-essential valgrind

    - name: Build with Makefile
      run: make

    - name: Run Valgrind to check for memory leaks
      run: |
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./build/Test.exe 1000 1 1000
